version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains airbnb listings
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null
      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of the apartment 
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: minimum_nights stayed
        tests:
          - positive_value
  - name: dim_hosts_cleansed
    description: Cleansed table which contains hist information
    columns:
      - name: host_id
        description: Primary key for the hosts
      - name: host_name
        description: name of host
      - name: is_superhost
        description: boolean value to indicate superhost 
      - name: created_at
        description: created_at field
      - name: updated_at
        description: update at field
  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number


      